---
- hosts: all
  vars:
    nodejs_guest_dir: /opt
  become: true
  tasks:
     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Install Gui
       apt: name={{item}} state=latest install_recommends=no # THis style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
       with_items:
         - ubuntu-desktop
         - indicator-session # https://askubuntu.com/questions/362556/why-cant-i-shut-down-after-installing-ubuntu-desktop-from-minimal-cd
         - gnome-terminal # after seeing it was not installed

     # Only needed until we change the vagrant box we are using
     - name: add vagrant user
       user: 
         name: vagrant
         password: "{{ 'test1'|password_hash('sha256') }}"

     - name: Install Key packages
       apt: name={{item}} state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
       with_items:
         - apache2
         - ruby
         - ruby-all-dev

     - name: Ready to install Node 9 # as advised https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
       shell: "curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -"

     - name: Install Node 9
       apt: name={{item}} state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
       with_items:
         - nodejs 

     - gem:
         name: "{{ item }}"
         state: present
         user_install: no
       with_items:
         - sass

     - name: Set startup script
       copy:
         src: files/scripts/startup_config.sh
         dest: /home/vagrant/bin/
         owner: vagrant
         group: vagrant
         mode: 0744 

     - name: initiate script for startup
       copy:
         src: files/scripts/.gnomerc
         dest: /home/vagrant/.gnomerc
         owner: vagrant
         group: vagrant
         mode: 0744

     - name: copy web files
       copy:
         src: files/website/
         dest: /var/www/html
         mode: 0744

#     - name: Compile scss file
#       shell: scss /var/www/html/css/table1.scss /var/www/html/css/table1.css


     - name: Create missing locales # https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
       command: sudo locale-gen "en_GB.UTF-8"

#     - name: pt2
#       command: sudo dpkg-reconfigure locales

     - name: dev locale
       action: command sudo update-locale LC_ALL=en_GB.utf8

     - name: set default locale
       sudo: yes
       lineinfile: dest=/etc/default/locale
         regexp="LC_ALL"
         line="LC_ALL=\"en_GB.utf8\""


#     - name: Change text entry to GB #https://askubuntu.com/questions/861662/setting-text-entry-setting-in-ubuntu-16-04-using-terminal
#       command: gsettings set org.gnome.desktop.input-sources sources "[('xkb','gb')]"
#       become_user: vagrant

     - name: Copy nodejs files across
       sudo: yes
       copy: 
         src: files/nodejs
         dest: /opt

     - name: Install npm dependencies
#       npm: Bug reported https://github.com/ansible/ansible/issues/33555
#         path: /opt/nodejs/provisioner
       command: npm install
       args:
         chdir: /opt/nodejs/provisioner
         creates: /opt/nodejs/provisioner/node_modules/

     - name: Enable Apache proxy http module
       apache2_module:
         state: present
         name: proxy_http

     - name: Add proxy path
       copy:
         src: files/apache2/conf/proxy.conf
         dest: /etc/apache2/mods-enabled/proxy.conf

     - name: Reset Apache service
       service:
         name: apache2
         state: reloaded

