---
- hosts: all
  become: true
  tasks:
     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Install Gui
       apt: name={{item}} state=latest install_recommends=no # THis style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
       with_items:
         - ubuntu-desktop
         - indicator-session # https://askubuntu.com/questions/362556/why-cant-i-shut-down-after-installing-ubuntu-desktop-from-minimal-cd
         - gnome-terminal # after seeing it was not installed

     # Only needed until we change the vagrant box we are using
     - name: add vagrant user
       user: 
         name: vagrant
         password: "{{ 'test1'|password_hash('sha256') }}"

     - name: Install apache server
       apt: name=apache2

     - name: Set startup script
       copy:
         src: files/startup_config.sh
         dest: /home/vagrant/bin/
         owner: vagrant
         group: vagrant
         mode: 0744 

     - name: initiate script for startup
       copy:
         src: files/.gnomerc
         dest: /home/vagrant/.gnomerc
         owner: vagrant
         group: vagrant
         mode: 0744

     - name: Create missing locales # https://askubuntu.com/questions/162391/how-do-i-fix-my-locale-issue
       command: sudo locale-gen "en_GB.UTF-8"

#     - name: pt2
#       command: sudo dpkg-reconfigure locales

     - name: dev locale
       action: command sudo update-locale LC_ALL=en_GB.utf8

     - name: set default locale
       sudo: yes
       lineinfile: dest=/etc/default/locale
         regexp="LC_ALL"
         line="LC_ALL=\"en_GB.utf8\""


#     - name: Change text entry to GB #https://askubuntu.com/questions/861662/setting-text-entry-setting-in-ubuntu-16-04-using-terminal
#       command: gsettings set org.gnome.desktop.input-sources sources "[('xkb','gb')]"
#       become_user: vagrant
