---
# file: roles/nodejs/tasks/main.yml


# Install nodejs from specific repo
- name: Ready to install Node 10 # as advised https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"

- name: Install Node 10
  become: true
  apt: name={{item}} state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
  with_items:
    - nodejs 
- name: set base dev dir
  file:
    path: /home/vagrant/dev
    state: directory

- name: create symlink
  file: 
    src: /vagrant/ansible/roles/nodejs/files/nodejs
    dest: /home/vagrant/dev/nodejs
    state: link

#- name: Install npm dependencies for provisioner project
#  command: npm install
#  args:
#    chdir: /home/vagrant/dev/nodejs/provisioner
#    creates: /home/vagrant/dev/provisioner/node_modules/

# add yarn
- name: identify yarn repo
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
  
- name: attach repo
  shell: 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'

# add yarn
- name: identify yarn repo
  shell: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
  
- name: attach repo
  shell: 'echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'

- name: Update apt-cache
  become: true
  apt:
    update_cache: yes

- name: Install yarn   
  become: true
  apt: name={{item}} state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
  with_items:
    - yarn

- name: Add localhostt to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1      localhost localhostt'
    owner: root
    group: root
    mode: 0644

