---
# file: roles/nodejs/tasks/main.yml


# Install nodejs from specific repo
- name: Ready to install Node 10 # as advised https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
  shell: "curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -"

- name: Install Node 10
  become: true
  apt: name={{item}} state=latest install_recommends=no # This style described in http://docs.ansible.com/ansible/latest/playbooks_loops.html#standard-loops
  with_items:
    - nodejs 
- name: set base dev dir
  file:
    path: /home/vagrant/dev
    state: directory

- name: create symlink
  file: 
    src: /vagrant/ansible/roles/nodejs/files/nodejs
    dest: /home/vagrant/dev/nodejs
    state: link

- name: Install npm dependencies for provisioner project
  command: npm install
  args:
    chdir: /home/vagrant/dev/nodejs/provisioner
    creates: /home/vagrant/dev/provisioner/node_modules/

